name: 0-build-snapshot-win
# 2023-08-06 09:00

on:
  workflow_dispatch:
  workflow_call:
#  push:
#    paths:
#    - 'components/**'
#    - 'plugins/**'
#    - 'sdk/**'
#    - 'src/**'
#    branches:
#      - master

env:
  TAG_NAME: "doublecmd"

#concurrency:
#  group: ${{ github.ref }}
#  cancel-in-progress: true

jobs:
  build-win:
    runs-on: windows-latest
    steps:

    - name: Checkout source
      uses: deep-soft/checkout@v3
      with:
        fetch-depth: 0

    - name: Set DC_VER
      shell: bash
      run: |
        # set -x;
        _version_major_=$(grep "MajorVersionNr Value="       src/doublecmd.lpi | awk -F = '{print $2}' | awk -F / '{print $1}' | tr -d '"' );
        _version_minor_=$(grep "MinorVersionNr Value="       src/doublecmd.lpi | awk -F = '{print $2}' | awk -F / '{print $1}' | tr -d '"' );
        echo "_version_major_=" $_version_major_;
        echo "_version_minor_=" $_version_minor_;
        _prog_version_="$_version_major_.$_version_minor_.0";
        echo "DC_VER=$_prog_version_" >> $GITHUB_ENV;

    - name: Print DC_VER
      shell: bash
      run: |
        echo "DC_VER=${{ env.DC_VER }}";

    - name: Archive src Release
      uses: deep-soft/zip-release@main
      with:
        type: 'zip'
        filename: '${{ env.TAG_NAME }}-${{ env.DC_VER }}-src-win.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig doublecmd.app doublecmd-release/*'

    - name: Install Lazarus
      uses: deep-soft/setup-fpc@win
      with:
        lazarus-version: "2.2.6"

    - name: Build packages
      shell: cmd
      run: |
        cd ./.github/scripts/
        call create_snapshot_pv.bat

    - name: Publish Release
      continue-on-error: true
      uses: deep-soft/action-gh-release@v1
      with:
        draft: true
        tag_name: ${{ env.TAG_NAME }}-${{ env.DC_VER }}-${{ env.DC_REVISION }}-win
        files: |
          ./doublecmd-release/*.7z
          ./doublecmd-release/*.txt
          ${{ env.ZIP_RELEASE_ARCHIVE }}

    - name: Prepare to deploy to snapshot server
      continue-on-error: true
      shell: bash
      run: |
        # mv '${{ env.TAG_NAME }}-${{ env.DC_VER }}.7z' doublecmd-release/;
        mv ${{ env.ZIP_RELEASE_ARCHIVE }} doublecmd-release/;
        bash ./.github/scripts/upload_snapshot_pv_pre.sh;

    - name: Deploy to snapshot server
      continue-on-error: true
      shell: bash
      run: bash ./.github/scripts/upload_snapshot_pv.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SSH_PRIVATE_KEY_P: ${{ secrets.SERVER_SSH_KEY_P }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}

    - name: Print REVISION
      continue-on-error: true
      shell: bash
      run: |
        echo "Version: ${{ env.DC_VER }}";
        echo "Revision: ${{ env.DC_REVISION }}";
