name: 0-build-snapshot-mac
# 2023-08-06 09:00

on:
  workflow_dispatch:
  workflow_call:
#  push:
#    paths:
#    - 'components/**'
#    - 'plugins/**'
#    - 'sdk/**'
#    - 'src/**'
#    branches:
#      - master

env:
  TAG_NAME: "doublecmd"

#concurrency:
#  group: ${{ github.ref }}
#  cancel-in-progress: true

jobs:
  build-mac:
    runs-on: macos-11
    steps:

    - name: Checkout source
      uses: deep-soft/checkout@v3
      with:
        fetch-depth: 0

    - name: Set DC_VER
      shell: bash
      run: |
        # set -x;
        _version_major_=$(grep "MajorVersionNr Value="       src/doublecmd.lpi | awk -F = '{print $2}' | awk -F / '{print $1}' | tr /d \" );
        _version_minor_=$(grep "MinorVersionNr Value="       src/doublecmd.lpi | awk -F = '{print $2}' | awk -F / '{print $1}' | tr /d \" );
        echo "_version_major_=" $_version_major_;
        echo "_version_minor_=" $_version_minor_;
        _prog_version_="$_version_major_.$_version_minor_.0";
        echo "DC_VER=$_prog_version_" >> $GITHUB_ENV;

    - name: Print DC_VER
      shell: bash
      run: |
        echo "DC_VER=${{ env.DC_VER }}";

    - name: Archive src Release
      uses: deep-soft/zip-release@v1
      with:
        type: 'tar.xz'
        filename: '${{ env.TAG_NAME }}-${{ env.DC_VER }}.tar.xz'
        directory: '.'
        exclusions: '*.git* /*node_modules/* .editorconfig doublecmd-release/*'

    - name: Get Lazarus source
      uses: deep-soft/checkout@v3
      with:
        repository: 'fpc/Lazarus'

    - name: Install Free Pascal
      uses: deep-soft/setup-fpc@master
      with:
        lazarus-version: "stable"

    - name: Build and install Lazarus
      run: |
        make all install

    - name: Create Lazarus config
      shell: bash
      run: |
        sudo mkdir -p /etc/lazarus;
        sudo cp tools/install/macosx/environmentoptions.xml /etc/lazarus/environmentoptions.xml;
        sudo sed -i -e "s|_PPCARCH_|fpc|g; s|/Developer/lazarus|/usr/local/share/lazarus|g" /etc/lazarus/environmentoptions.xml;

    - name: Build packages
      shell: bash
      run: |
        pwd;
        bash ./.github/scripts/create_snapshot_pv.sh;

    - name: Publish Release
      continue-on-error: true
      uses: deep-soft/action-gh-release@v1
      with:
        draft: true
        tag_name: ${{ env.TAG_NAME }}-${{ env.DC_VER }}-${{ env.DC_REVISION }}-mac
        files: |
          ./doublecmd-release/*.dmg
          ./doublecmd-release/*.php
          '${{ env.TAG_NAME }}-${{ env.DC_VER }}.tar.xz'

    - name: Prepare to deploy to snapshot server
      continue-on-error: true
      shell: bash
      run: |
        mv '${{ env.TAG_NAME }}-${{ env.DC_VER }}.tar.xz' doublecmd-release/;
        bash ./.github/scripts/upload_snapshot_pv_pre.sh;

    - name: Deploy to snapshot server
      continue-on-error: true
      shell: bash
      run: |
        bash ./.github/scripts/upload_snapshot_pv.sh;
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SSH_PRIVATE_KEY_P: ${{ secrets.SERVER_SSH_KEY_P }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}

    - name: Print REVISION
      continue-on-error: true
      shell: bash
      run: |
        echo "Version: ${{ env.DC_VER }}";
        echo "Revision: ${{ env.DC_REVISION }}";
